"""fix_supersedes_fk_on_delete

Revision ID: cd362cd2e8e7
Revises: fe0a0e461642
Create Date: 2026-05-31 18:48:52.300127

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'cd362cd2e8e7'
down_revision: Union[str, Sequence[str], None] = 'fe0a0e461642'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(op.f('memories_supersedes_id_fkey'), 'memories', type_='foreignkey')
    op.create_foreign_key(None, 'memories', 'memories', ['supersedes_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'memories', type_='foreignkey')
    op.create_foreign_key(op.f('memories_supersedes_id_fkey'), 'memories', 'memories', ['supersedes_id'], ['id'])
    # ### end Alembic commands ###
